# -*- coding: utf-8 -*-
"""basic01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/AMendezCerquera/b80add03720421c8889be00d6f15471c/basic01.ipynb

Create five variables
"""

first_name = 'Alejandro'
firstName = 'Alejandro'
FirstName = 'Alejandro'
FIRSTNAME = 'Alejandro'

print(first_name)
print(firstName)
print(FirstName)
print(FIRSTNAME)

"""Create 10 Last Name Variables"""

last_name1 = "Mendez"
last_name2 = "Dufus"
last_name3 = "Silver"
last_name4 = "Joker"
last_name5 = "Lopez"
last_name6 = "Garcia"
last_name7 = "Gomez"
last_name8 = "Cerquera"
last_name9 = "Garzuzo"
last_name10 = "Gaitan"

"""Using a for loop to print all the Last Names"""

for x in range (1, 11):
  currentVariable = "last_name" + str(x)
  print (globals()[currentVariable])

"""Create 10 Lists, 10 Bool and 10 Floats"""

#Creating 10 Lists
list1 = [True, False, True]
list2 = ["1", "2", "3"]
list3 = [1, 2, 3, 4]
list4 = [[1, 2] , [3, 4]]
list5 = ["cold", "hot"]
list6 = [1, "warm", 3]
list7 = [3.14, 3.1416]
list8 = ["True", False]
list9 = [9, "9"]

studying = True
working = False
#List of two variables
list10 = [studying, working]

#Creating 10 Bools
hungry = True 
sleepy = True
tired = True
happy = True
true = True
false = False
playingMusic = True
haveWorkToday = True

#Creating 10 Floats
float1 = 3.14
float2 = 3.1
float3 = 1.68
float4 = 0.12
float5 = 0.21
float6 = 3.146
float7 = 3.12
float8 = 1.683
float9 = 0.124
float10 = 0.215

myDict = {"key1":"value1", "key2":"value2", "key3":"value3"}
myDict

type(myDict)

"""Create: <br>
dict1 = 10 foods <br>
dict2 = 10 people names <br>
dict3 = 5 sports players
"""

dict1 = {"food1":"Pizza",
         "food2":"Spaghetti",
         "food3":"Lasagna",
         "food4":"Bandeja Paisa",
         "food5":"Rice and Beans",
         "food6":"Rice and Chicken",
         "food7":"Rice and Eggs",
         "food8":"Rice",
         "food9":"Bento",
         "food10":"Miso Soup"}
dict1

dict2 = {"name1":"Alejandro",
         "name2":"Glope",
         "name3":"Genghis",
         "name4":"Ace",
         "name5":"Marc",
         "name6":"Mohsin",
         "name7":"MJ",
         "name8":"Sofia",
         "name9":"Andrea",
         "name10":"Irving"}
dict2

dict3 = {"soccerPlayer1":"Lionel Messi",
         "soccerPlayer2":"Cristiano Ronaldo",
         "soccerPlayer3":"Ronaldinho",
         "soccerPlayer4":"Neymar",
         "soccerPlayer5":"Marc ter Stegen"}
dict3